### PR TITLE
updated for Hapi 17

### PR DESCRIPTION
**Pull request by ArsalanDotMe**
I have updated this library to be compatible with Hapi 17+. All tests are now passing. Please merge and update the npm package.

### CODE REVIEW

**Comment by bs1180** [comment]
Wow, thanks :) This had been rather abandoned so your PR is very much appreciated. Would you like to add yourself as an author in the package.json and I'll make you a contributor?

**Comment by ArsalanDotMe** [comment]
Sure, thanks! I’ll add my name to the list and update the PR.

**Comment by ArsalanDotMe** [comment]
Hi, I've added my name and email to the contributors list in package.json. You can now merge the PR and add me as a contributor to the package

**Comment by ArsalanDotMe** [comment]
Hey man, any updates on this front? I'm currently pulling the npm package from my own github repo but it would be great if I could reference the original package from npm

**Comment by bs1180** [comment]
Sorry for the delay, I had some problems with 2FA. Now published to NPM, and also added you as a collaborator on Github :)

Thanks again!

**Comment by ArsalanDotMe** [comment]
Thanks man! Great to join your wonderful library, its very useful!

**Comment by ArsalanDotMe** [comment]
I'm using this to create a sort-of clone of [localtunnel](https://localtunnel.github.io/www/)

**Pull request merged**
